[ENVIRONMENT]
# Available Environments:
# - Classic Control: CartPole-v1, MountainCar-v0, Acrobot-v1
# - Atari: ALE/SpaceInvaders-v5, ALE/Adventure-v5, ALE/Alien-v5
#          ALE/AirRaid-v5, ALE/Asteroids-v5, ALE/Pong-v5

env_id = ALE/Pong-v5
evaluation = 0
render = 0
seed = 42

[MODEL]
hidden_size = 1024

[PPO]
lambda = 0.95
ppo_epochs = 3
ppo_clip_eps = 0.15
value_coef = 0.9
entropy_coef = 0.05

[TRAINING]
learning_rate = 3e-4
batch_size = 4096
gamma = 0.99
evaluation_episodes = 5
num_iterations = 1
max_train_steps = 20_000_000
max_episode_steps = 100_000
